# Le decimos a Spring que por defecto arranque en el perfil "dev"
spring.profiles.active=dev

# Configuramos nuestros datos base
app.info.name=Gestor de Inventario
# @project.version@ tomará la versión automáticamente del pom.xml gracias al filtrado que configuramos
app.info.version=@project.version@
app.info.developerEmail=hdarmijos002@gmail.com
